# Generated by Django 2.2.5 on 2020-08-13 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('null', 'null')], default='null', max_length=10)),
                ('avatar', models.CharField(blank=True, default='', max_length=150)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('addressee', models.CharField(default='', max_length=50)),
                ('membership', models.IntegerField(default=0)),
                ('region', models.CharField(default='', max_length=50)),
                ('current_captain_id', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='FarmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('contact', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('short', models.CharField(blank=True, default='', max_length=20)),
                ('longitude', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('main_video', models.CharField(max_length=200)),
                ('main_pic', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive'), (2, 'expire')], default=0)),
                ('mode', models.IntegerField(choices=[(0, 'all'), (1, 'foster'), (2, 'selling')], default=0)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(default='', max_length=15)),
                ('effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='Prepay_Order',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('noncestr', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=40)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_id', models.IntegerField()),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('varified', models.BooleanField(default=False)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
                ('captain_id', models.IntegerField(blank=True, default=-1)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Varify_failed',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('num', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('price_origin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('captain_id', models.IntegerField(blank=True, default=-1)),
                ('num_delivered', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=400)),
                ('genre', models.CharField(choices=[('adopt', 'adopt'), ('sell', 'sell')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wxapp.Item')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='wxapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(default=0)),
                ('comment_text', models.CharField(max_length=100)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_avatar', models.CharField(blank=True, default='', max_length=150)),
                ('user_nickname', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('genre', models.IntegerField(choices=[(1, 'comments'), (2, 'purches')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('address', models.CharField(max_length=40)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('dis_name', models.CharField(blank=True, default='', max_length=20)),
                ('time_of_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.IntegerField(choices=[(0, '全部'), (1, '销售'), (2, '配送')], default=0)),
                ('commission_m', models.DecimalField(decimal_places=2, max_digits=2)),
                ('commission_d', models.DecimalField(decimal_places=2, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wxapp.AppUser')),
            ],
        ),
    ]
