# Generated by Django 2.2.5 on 2020-12-26 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('null', 'null')], default='null', max_length=10)),
                ('avatar', models.CharField(blank=True, default='', max_length=150)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('addressee', models.CharField(default='', max_length=50)),
                ('membership', models.IntegerField(default=0)),
                ('region', models.CharField(default='', max_length=50)),
                ('current_captain_id', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('address', models.CharField(max_length=40)),
                ('phonenumber', models.BigIntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('dis_name', models.CharField(blank=True, default='', max_length=20)),
                ('time_of_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliver', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('commission_m', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('commission_d', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wxapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='FarmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('contact', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('short', models.CharField(blank=True, default='', max_length=20)),
                ('lng', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('commission_rate', models.PositiveIntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('video_address', models.CharField(max_length=200)),
                ('pic_address', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'expire')], default=0)),
                ('mode', models.IntegerField(choices=[(0, 'all'), (1, 'foster'), (2, 'selling')], default=0)),
                ('effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('commission_rate', models.PositiveIntegerField(default=25)),
                ('max_cut', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='Prepay_Order',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('noncestr', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=40)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_id', models.IntegerField()),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('varified', models.BooleanField(default=False)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
                ('captain_id', models.IntegerField(blank=True, default=-1)),
                ('message', models.CharField(max_length=400, null=True)),
                ('nickname', models.CharField(default='', max_length=20, null=True)),
                ('post_sign', models.CharField(default='', max_length=40, null=True)),
                ('genre', models.CharField(choices=[('adopt', 'adopt'), ('sell', 'sell')], default='sell', max_length=10)),
                ('commission_rate', models.PositiveIntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('grade', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=32)),
                ('option_A', models.CharField(max_length=32)),
                ('option_B', models.CharField(max_length=32)),
                ('option_C', models.CharField(max_length=32)),
                ('option_D', models.CharField(max_length=32)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=8)),
                ('uploader', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Varify_failed',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(default='', max_length=15)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sell', to='wxapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('num', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('farm_name', models.CharField(blank=True, default='', max_length=30)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('imageUrl', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('captain_id', models.IntegerField(blank=True, default=-1)),
                ('num_delivered', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('genre', models.CharField(choices=[('adopt', 'adopt'), ('sell', 'sell')], max_length=10)),
                ('nickname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('post_sign', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('commission_rate', models.PositiveIntegerField(default=25)),
                ('cap', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='wxapp.Captain')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wxapp.Item')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='wxapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(default=-1, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(default=0)),
                ('comment_text', models.CharField(max_length=100)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_avatar', models.CharField(blank=True, default='', max_length=150)),
                ('user_nickname', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('genre', models.IntegerField(choices=[(1, 'comments'), (2, 'purches')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('guaranteed', models.FloatField(default=0)),
                ('benefit', models.CharField(default='', max_length=200)),
                ('period', models.IntegerField(blank=True, default=1)),
                ('unit', models.CharField(default='', max_length=5)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Adopt', to='wxapp.Item')),
            ],
        ),
    ]
