# Generated by Django 2.2.5 on 2020-08-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_auto_20200813_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main_pic',
            new_name='pic_address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='main_video',
            new_name='video_address',
        ),
    ]
