# Generated by Django 2.2.5 on 2020-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0005_auto_20200818_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='prepay_order',
            name='deliver_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
