# Generated by Django 2.2.5 on 2020-08-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0006_auto_20200819_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price2',
        ),
    ]
