# Generated by Django 2.2.5 on 2020-08-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0008_auto_20200826_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='sign',
        ),
    ]
