# Generated by Django 2.2.5 on 2020-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0012_auto_20200826_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nickname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_sign',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='prepay_order',
            name='nickname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepay_order',
            name='post_sign',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
