# Generated by Django 2.2.5 on 2020-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0013_auto_20200826_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepay_order',
            name='deliver_time',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prepay_order',
            name='message',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
