# Generated by Django 2.2.5 on 2020-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0014_auto_20200826_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imageUrl',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
