# Generated by Django 2.2.5 on 2020-08-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0016_remove_prepay_order_deliver_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='guaranteed',
            new_name='guaranted',
        ),
    ]
