# Generated by Django 2.2.5 on 2020-08-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0017_auto_20200829_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='guaranted',
            new_name='guaranteed',
        ),
    ]
