# Generated by Django 2.2.5 on 2020-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0018_auto_20200829_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='benefit',
            field=models.CharField(default='', max_length=200),
        ),
    ]
