# Generated by Django 2.2.5 on 2020-08-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0019_auto_20200831_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='captain_obj',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxapp.Captain'),
        ),
    ]
