# Generated by Django 2.2.5 on 2020-08-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0022_auto_20200831_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cap',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='wxapp.Captain'),
        ),
    ]
