# Generated by Django 2.2.5 on 2020-09-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0023_auto_20200831_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='diliver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='captain',
            name='marketing',
            field=models.BooleanField(default=True),
        ),
    ]
