# Generated by Django 2.2.5 on 2020-09-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0025_auto_20200902_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='diliver',
            new_name='deliver',
        ),
    ]
