# Generated by Django 2.2.5 on 2020-09-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0028_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
