# Generated by Django 2.2.5 on 2020-09-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0029_auto_20200908_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmuser',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='farmuser',
            old_name='longitude',
            new_name='lng',
        ),
    ]
