# Generated by Django 2.2.5 on 2020-09-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0030_auto_20200928_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='captain',
            old_name='longitude',
            new_name='lng',
        ),
    ]
