# Generated by Django 2.2.5 on 2020-10-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0031_auto_20200929_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemShadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveitemid', models.IntegerField(default=-1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.Item')),
            ],
        ),
    ]
