# Generated by Django 2.2.5 on 2020-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0032_itemshadow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemshadow',
            name='liveitemid',
        ),
        migrations.AddField(
            model_name='itemshadow',
            name='goods_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
