# Generated by Django 2.2.5 on 2020-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0033_auto_20201021_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmuser',
            name='commission_rate',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='item',
            name='commission_rate',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='prepay_order',
            name='commission_rate',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
