# Generated by Django 2.2.5 on 2020-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0034_auto_20201117_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('grade', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=32)),
                ('option_A', models.CharField(max_length=32)),
                ('option_B', models.CharField(max_length=32)),
                ('option_C', models.CharField(max_length=32)),
                ('option_D', models.CharField(max_length=32)),
                ('correct_anwser', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=8)),
                ('uploader', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
