# Generated by Django 2.2.5 on 2020-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0036_auto_20201209_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_cut',
            field=models.IntegerField(default=0),
        ),
    ]
