# Generated by Django 2.2.5 on 2020-12-26 21:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wxapp', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phonenumber', models.BigIntegerField(blank=True, default=0, unique=True)),
                ('farm', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('farmuser', 'farmuser'), ('manager', 'manager'), ('admin', 'admin')], default='farmuser', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('extractable', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('appid', models.CharField(default='', max_length=50)),
                ('secret', models.CharField(default='', max_length=50)),
                ('mch_id', models.CharField(default='', max_length=50)),
                ('mch_key', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PicFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('itemname', models.CharField(blank=True, default='', max_length=50)),
                ('farmid', models.CharField(default='', max_length=50)),
                ('pic', models.FileField(unique=True, upload_to='statics/pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TcVideo',
            fields=[
                ('fileid', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('video_name', models.CharField(max_length=32)),
                ('video_url', models.CharField(max_length=256)),
                ('cover_url', models.CharField(max_length=256)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('farmid', models.CharField(default='', max_length=50)),
                ('video', models.FileField(unique=True, upload_to='statics/video/')),
                ('cover', models.FileField(blank=True, upload_to='statics/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.Account')),
            ],
            bases=('homepage.account',),
        ),
        migrations.CreateModel(
            name='VIMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('item_id', models.IntegerField(default=-1)),
                ('video_id', models.IntegerField(default=-1)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('genre', models.IntegerField(choices=[(-1, 'expense'), (1, 'income')])),
                ('msg', models.CharField(default='', max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account')),
            ],
        ),
        migrations.CreateModel(
            name='tcVideo2Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.Item')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.TcVideo')),
            ],
        ),
        migrations.CreateModel(
            name='Permission2Action2Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p2a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Action')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Menu')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='CashingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_done', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('msg', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '待办'), (2, '办理中'), (3, '完成'), (4, '关闭')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banknum', models.CharField(default='', max_length=48)),
                ('receiver', models.CharField(max_length=24)),
                ('bankname', models.CharField(max_length=48)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='bankinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.BankInfo'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='farminfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wxapp.FarmUser'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
