# Generated by Django 2.2.5 on 2020-08-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_videofiles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='cover',
            field=models.FileField(blank=True, upload_to='statics/cover/'),
        ),
    ]
