# Generated by Django 2.2.5 on 2020-12-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_testmo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMo',
        ),
    ]
