# Generated by Django 2.2.5 on 2020-11-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0033_auto_20201021_0850'),
        ('homepage', '0004_auto_20200817_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TcVideo',
            fields=[
                ('fileid', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('video_name', models.CharField(max_length=32)),
                ('video_url', models.CharField(max_length=128)),
                ('cover_url', models.CharField(max_length=128)),
                ('FarmUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapp.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='Permission2Action2Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p2a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Action')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Menu')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Permission')),
            ],
        ),
    ]
