# Generated by Django 2.2.5 on 2020-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_action_menu_permission_permission2action_permission2action2role_role_tcvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcvideo',
            old_name='FarmUser',
            new_name='farmuser',
        ),
        migrations.AlterField(
            model_name='tcvideo',
            name='cover_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tcvideo',
            name='video_url',
            field=models.CharField(max_length=256),
        ),
    ]
