# Generated by Django 2.2.5 on 2020-11-15 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201114_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcvideo',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
