# Generated by Django 2.2.5 on 2020-11-17 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20201117_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='num',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transact',
            old_name='desc',
            new_name='msg',
        ),
        migrations.AddField(
            model_name='account',
            name='bankAccountNum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='genre',
            field=models.IntegerField(choices=[(-1, 'expense'), (1, 'income')]),
        ),
        migrations.CreateModel(
            name='CashingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('msg', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '待办'), (2, '办理中'), (3, '完成')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Account')),
            ],
        ),
    ]
