# Generated by Django 2.2.5 on 2020-11-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20201118_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcvideo',
            old_name='AdminUser',
            new_name='farmuser',
        ),
    ]
