# Generated by Django 2.2.5 on 2020-11-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20201118_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashingrequest',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '待办'), (2, '办理中'), (3, '完成'), (4, '关闭')]),
        ),
        migrations.AlterField(
            model_name='transact',
            name='msg',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=24)),
                ('bankname', models.CharField(max_length=48)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
