# Generated by Django 2.2.5 on 2020-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20201123_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='banknum',
            field=models.CharField(default='', max_length=48),
        ),
    ]
