# Generated by Django 2.2.5 on 2020-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20201123_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashingrequest',
            name='time_done',
            field=models.DateTimeField(null=True),
        ),
    ]
