# Generated by Django 2.2.5 on 2020-11-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_cashingrequest_time_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='bankinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.BankInfo'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
