# Generated by Django 2.2.5 on 2020-11-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20201124_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bankAccountNum',
        ),
    ]
